{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-29T21:51:03.617Z","ID_EVENTO":7329,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-29 15:51:03"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-29T21:51:03.654Z","ID_EVENTO":7330,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-29 15:51:03"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:29.803Z","ID_EVENTO":7331,"ID_PROCESO":8,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:29"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:29.849Z","ID_EVENTO":7332,"ID_PROCESO":8,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:51.184Z","ID_EVENTO":7333,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:51"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:58:37.726Z","ID_EVENTO":7334,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:58:37"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:58:46.256Z","ID_EVENTO":7335,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:58:46"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:59:00.962Z","ID_EVENTO":7336,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:59:00"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:59:13.957Z","ID_EVENTO":7337,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:59:13"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:00:39.680Z","ID_EVENTO":7338,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:00:39"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:01:38.753Z","ID_EVENTO":7339,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:01:38"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:06:54.795Z","ID_EVENTO":7340,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:06:54"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:46:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:09:38.117Z","ID_EVENTO":7341,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:09:38"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:46:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:10:48.564Z","ID_EVENTO":7342,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:10:48"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No existe valor para llave primaria  ID_QUINIELA ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:01:58.846Z","ID_EVENTO":7343,"ID_PROCESO":7,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Bulk Update: 'No existe valor para llave primaria  ID_QUINIELA '.","level":"error","message":"Error ","timestamp":"2025-08-30 19:01:58"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:18.157Z","ID_EVENTO":7345,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:18"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:20.254Z","ID_EVENTO":7347,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:20"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:20.809Z","ID_EVENTO":7349,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:20"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:21.267Z","ID_EVENTO":7351,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:21"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:21.791Z","ID_EVENTO":7353,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:21"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:22.356Z","ID_EVENTO":7355,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:22"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:22.861Z","ID_EVENTO":7357,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:22"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:23.777Z","ID_EVENTO":7359,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:23"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:12:05.214Z","ID_EVENTO":7361,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:12:05"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.bulkUpdate (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:366:12)\n    at async Q_QUIN_PARTICIPANTE.update (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2010:28)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:55:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async updateRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:54:27)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:104:31\n    at async C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:507:18","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T16:59:29.809Z","ID_EVENTO":7362,"ID_PROCESO":2,"MSG_ERROR":"DatabaseError en Ejecucion Crud/Bulk Update. Mensaje de Sequelize: 'String or binary data would be truncated.'. Mensaje original de DB: 'String or binary data would be truncated.'. SQL: 'UPDATE [dbo].[Q_QUIN_PARTICIPANTE] SET [ID_QUINIELA]=@0,[ID_PARTICIPANTE]=@1,[ID_PERIODO]=@2,[ID_PARTIDO]=@3,[CVE_GANADOR]=@4 WHERE [ID_QUINIELA] = @5 AND [ID_PARTICIPANTE] = @6 AND [ID_PERIODO] = @7 AND [ID_PARTIDO] = @8'","level":"error","message":"Error ","timestamp":"2025-08-31 10:59:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No existen datos a actualizar","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T17:36:47.661Z","ID_EVENTO":7363,"ID_PROCESO":7,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Bulk Update: 'No existen datos a actualizar'.","level":"error","message":"Error ","timestamp":"2025-08-31 11:36:47"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T02:08:10.107Z","ID_EVENTO":7364,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-01 20:08:10"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T02:08:11.145Z","ID_EVENTO":7365,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-01 20:08:11"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T02:08:13.167Z","ID_EVENTO":7366,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-01 20:08:13"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T03:11:03.696Z","ID_EVENTO":7367,"ID_PROCESO":15,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-01 21:11:03"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T03:11:03.718Z","ID_EVENTO":7368,"ID_PROCESO":15,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-01 21:11:03"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"TypeError: Cannot read properties of null (reading 'includes')\n    at formatQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/queryConsulta.js:123:15)\n    at ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:11:20)\n    at ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T03:11:17.525Z","ID_EVENTO":7369,"ID_PROCESO":15,"MSG_ERROR":"Error desconocido en Ejecucion de Query: {}.","level":"error","message":"Error ","timestamp":"2025-09-01 21:11:17"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:01:02.258Z","ID_EVENTO":7370,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:01:02"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:01:03.324Z","ID_EVENTO":7371,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:01:03"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:01:05.354Z","ID_EVENTO":7372,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:01:05"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:04:07.712Z","ID_EVENTO":7373,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:04:07"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:04:08.766Z","ID_EVENTO":7374,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:04:08"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:04:10.806Z","ID_EVENTO":7375,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:04:10"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T15:04:14.849Z","ID_EVENTO":7376,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-02 09:04:14"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Registro ya existe Q_SURVIVOR","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T18:10:04.496Z","ID_EVENTO":7377,"ID_PROCESO":2,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Create: 'Registro ya existe Q_SURVIVOR'.","level":"error","message":"Error ","timestamp":"2025-09-02 12:10:04"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Registro ya existe Q_SURVIVOR","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T18:11:23.923Z","ID_EVENTO":7378,"ID_PROCESO":2,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Create: 'Registro ya existe Q_SURVIVOR'.","level":"error","message":"Error ","timestamp":"2025-09-02 12:11:23"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Registro ya existe Q_SURVIVOR","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T18:23:53.242Z","ID_EVENTO":7379,"ID_PROCESO":2,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Create: 'Registro ya existe Q_SURVIVOR'.","level":"error","message":"Error ","timestamp":"2025-09-02 12:23:53"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Registro ya existe Q_SURVIVOR","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-02T21:45:18.481Z","ID_EVENTO":7380,"ID_PROCESO":2,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Create: 'Registro ya existe Q_SURVIVOR'.","level":"error","message":"Error ","timestamp":"2025-09-02 15:45:18"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-03T21:37:38.083Z","ID_EVENTO":7381,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-03 15:37:38"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-03T21:37:38.150Z","ID_EVENTO":7382,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-03 15:37:38"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:45.264Z","ID_EVENTO":7383,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:45"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:45.297Z","ID_EVENTO":7384,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:45"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:46.687Z","ID_EVENTO":7385,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:46"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:46.702Z","ID_EVENTO":7386,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:46"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:47.122Z","ID_EVENTO":7387,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:47"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:47.136Z","ID_EVENTO":7388,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:47"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:47.392Z","ID_EVENTO":7389,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:47"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:43:47.405Z","ID_EVENTO":7390,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:43:47"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:51:25.726Z","ID_EVENTO":7391,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:51:25"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:51:25.752Z","ID_EVENTO":7392,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:51:25"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.insert (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async FC_SEG_USUARIO.create (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:38:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async createRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:37:27)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:56:28.613Z","ID_EVENTO":7393,"ID_PROCESO":1,"MSG_ERROR":"DatabaseError en Registro de Usuario. Mensaje de Sequelize: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. Mensaje original de DB: 'The INSERT statement conflicted with the CHECK constraint \"CK01_CF_SEG_Usuario\". The conflict occurred in database \"NFLQUIN\", table \"dbo.FC_SEG_USUARIO\", column 'SIT_USUARIO'.'. SQL: 'INSERT INTO [dbo].[FC_SEG_USUARIO] ([CVE_USUARIO],[APELLIDO_PATERNO],[APELLIDO_MATERNO],[NOMBRE],[PASSWORD],[B_BLOQUEADO],[SIT_USUARIO],[CVE_IDIOMA],[CVE_PERFIL]) OUTPUT INSERTED.[CVE_USUARIO],INSERTED.[APELLIDO_PATERNO],INSERTED.[APELLIDO_MATERNO],INSERTED.[NOMBRE],INSERTED.[PASSWORD],INSERTED.[B_BLOQUEADO],INSERTED.[SIT_USUARIO],INSERTED.[CVE_IDIOMA],INSERTED.[CVE_PERFIL] VALUES (@0,@1,@2,@3,@4,@5,@6,@7,@8);'","level":"error","message":"Error ","timestamp":"2025-09-05 17:56:28"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-05T23:56:28.643Z","ID_EVENTO":7394,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Ha ocurrido un error inesperado.'.","level":"error","message":"Error ","timestamp":"2025-09-05 17:56:28"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Registro ya existe FC_SEG_USUARIO","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-06T18:09:06.944Z","ID_EVENTO":7395,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Registro de Usuario: 'Registro ya existe FC_SEG_USUARIO'.","level":"error","message":"Error ","timestamp":"2025-09-06 12:09:06"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Registro ya existe FC_SEG_USUARIO","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-06T18:09:06.995Z","ID_EVENTO":7396,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Registro ya existe FC_SEG_USUARIO'.","level":"error","message":"Error ","timestamp":"2025-09-06 12:09:07"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Registro ya existe FC_SEG_USUARIO","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-06T18:13:34.918Z","ID_EVENTO":7397,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Registro de Usuario: 'Registro ya existe FC_SEG_USUARIO'.","level":"error","message":"Error ","timestamp":"2025-09-06 12:13:34"}
{"CVE_APLICACION":"dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"admin","DESC_ERROR":"Registro ya existe FC_SEG_USUARIO","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-06T18:13:34.938Z","ID_EVENTO":7398,"ID_PROCESO":1,"MSG_ERROR":"Error de tipo string en Error en Creacion de Usuario: 'Registro ya existe FC_SEG_USUARIO'.","level":"error","message":"Error ","timestamp":"2025-09-06 12:13:34"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 19 (line 1 column 20)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:46:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-07T16:00:21.516Z","ID_EVENTO":7401,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-07 10:00:21"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 19 (line 1 column 20)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:49:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-07T16:11:34.864Z","ID_EVENTO":7402,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-07 10:11:34"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 19 (line 1 column 20)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:47:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-07T16:15:27.968Z","ID_EVENTO":7403,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-07 10:15:27"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 19 (line 1 column 20)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:47:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-07T16:17:31.579Z","ID_EVENTO":7404,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-07 10:17:31"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-07T17:53:12.098Z","ID_EVENTO":7405,"ID_PROCESO":14,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Incorrect syntax near 'GO'.'. Mensaje original de DB: 'Incorrect syntax near 'GO'.'. SQL: 'SELECT\r\n    ISNULL((SELECT SUM(q.COSTO_QUINIELA) FROM Q_PARTICIPANTE p INNER JOIN Q_QUINIELA q ON \r\n        p.ID_QUINIELA = q.ID_QUINIELA), 0) AS totalQuiniela,\r\n    ISNULL((SELECT SUM(COSTO_SURVIVOR) FROM Q_SURVIVOR s INNER JOIN Q_PERIODO p ON\r\n        s.ID_QUINIELA = p.ID_QUINIELA AND\r\n        s.ID_PERIODO = p.ID_PERIODO\r\n        WHERE s.B_PAGO = 1), 0) AS totalSurvivor,\r\n    ISNULL((SELECT SUM(IMP_PREMIO) FROM Q_PERIODO WHERE B_ABIERTO = 0), 0) AS totalPremio;\r\nGO'","level":"error","message":"Error ","timestamp":"2025-09-07 11:53:12"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-08T22:04:23.736Z","ID_EVENTO":7406,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-08 16:04:23"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-08T22:04:23.789Z","ID_EVENTO":7407,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-09-08 16:04:23"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T19:58:03.608Z","ID_EVENTO":7408,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 13:58:03"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T19:58:05.024Z","ID_EVENTO":7409,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 13:58:05"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T19:58:07.276Z","ID_EVENTO":7410,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 13:58:07"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T19:58:11.697Z","ID_EVENTO":7411,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 13:58:11"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:01:40.495Z","ID_EVENTO":7412,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:01:40"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:01:41.702Z","ID_EVENTO":7413,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:01:41"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:01:44.064Z","ID_EVENTO":7414,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:01:44"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:01:48.444Z","ID_EVENTO":7415,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:01:48"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:03:51.632Z","ID_EVENTO":7416,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:03:51"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:03:52.891Z","ID_EVENTO":7417,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:03:52"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:03:55.260Z","ID_EVENTO":7418,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:03:55"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecRawQueryById (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:12:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contQuery.js:27:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-09T20:03:59.690Z","ID_EVENTO":7419,"ID_PROCESO":3,"MSG_ERROR":"DatabaseError en Ejecucion de Query. Mensaje de Sequelize: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. Mensaje original de DB: 'Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.'. SQL: 'SELECT\n(\n    SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO AS periodo,\n        (SELECT NOM_PARTICIPANTE FROM Q_PARTICIPANTE WHERE ID_PARTICIPANTE = qp.ID_PARTICIPANTE) AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    WHERE\n        qp.ID_QUINIELA = 1 AND\n        qp.ID_PERIODO = '1'\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp.ID_PERIODO\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosPeriodo,\n(\n   SELECT\n        DENSE_RANK() OVER (ORDER BY SUM(qp.PUNTOS) DESC) AS Posicion,\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE AS Nombre,\n        SUM(qp.PUNTOS) AS Puntos\n    FROM\n        Q_QUIN_PARTICIPANTE qp\n    INNER JOIN\n        Q_PARTICIPANTE qp2 ON qp.ID_PARTICIPANTE = qp2.ID_PARTICIPANTE\n    WHERE\n        qp.ID_QUINIELA = 1\n    GROUP BY\n        qp.ID_QUINIELA,\n        qp.ID_PARTICIPANTE,\n        qp2.NOM_PARTICIPANTE\n    ORDER BY\n        Puntos DESC\n    FOR JSON PATH\n) AS puntosTotal\nFOR JSON PATH, WITHOUT_ARRAY_WRAPPER;'","level":"error","message":"Error ","timestamp":"2025-09-09 14:03:59"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:05.814Z","ID_EVENTO":7420,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:05"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:06.863Z","ID_EVENTO":7421,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:06"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:08.892Z","ID_EVENTO":7422,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:08"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:12.924Z","ID_EVENTO":7423,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:12"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:40.942Z","ID_EVENTO":7424,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:40"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:41.979Z","ID_EVENTO":7425,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:41"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T20:19:44.006Z","ID_EVENTO":7426,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 14:19:44"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:54:30.510Z","ID_EVENTO":7427,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:54:30"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:54:31.556Z","ID_EVENTO":7428,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:54:31"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:54:33.588Z","ID_EVENTO":7429,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:54:33"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:54:37.614Z","ID_EVENTO":7430,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:54:37"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:56:48.249Z","ID_EVENTO":7431,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:56:48"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:56:49.283Z","ID_EVENTO":7432,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:56:49"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:56:51.306Z","ID_EVENTO":7433,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:56:51"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-11T22:56:55.336Z","ID_EVENTO":7434,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-11 16:56:55"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:08:56.310Z","ID_EVENTO":7435,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:08:56"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:09:07.766Z","ID_EVENTO":7436,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:09:07"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:09:28.973Z","ID_EVENTO":7437,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:09:28"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:09:30.932Z","ID_EVENTO":7438,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:09:30"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:10:15.606Z","ID_EVENTO":7439,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:10:15"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:10:51.789Z","ID_EVENTO":7440,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:10:51"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:11:27.541Z","ID_EVENTO":7441,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:11:27"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:12:40.813Z","ID_EVENTO":7442,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:12:40"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:13:14.356Z","ID_EVENTO":7443,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:13:14"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:17:04.396Z","ID_EVENTO":7444,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:17:04"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"eavila@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T15:22:49.467Z","ID_EVENTO":7445,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-12 09:22:49"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T17:12:49.075Z","ID_EVENTO":7446,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-12 11:12:49"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T17:12:50.156Z","ID_EVENTO":7447,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-12 11:12:50"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T17:12:52.181Z","ID_EVENTO":7448,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-12 11:12:52"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-12T17:12:56.217Z","ID_EVENTO":7449,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-12 11:12:56"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:04:59.075Z","ID_EVENTO":7450,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-13 12:04:59"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:05:10.048Z","ID_EVENTO":7451,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-13 12:05:10"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:11:29.975Z","ID_EVENTO":7452,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 12:11:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:11:31.009Z","ID_EVENTO":7453,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 12:11:31"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:11:33.038Z","ID_EVENTO":7454,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 12:11:33"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T18:11:37.066Z","ID_EVENTO":7455,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 12:11:37"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: Unexpected non-whitespace character after JSON at position 86 (line 1 column 87)\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:44:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T19:53:02.699Z","ID_EVENTO":7456,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-09-13 13:53:02"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"dcruz@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:32:25.952Z","ID_EVENTO":7457,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:32:25"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"dcruz@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:32:26.986Z","ID_EVENTO":7458,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:32:26"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"dcruz@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:32:29.018Z","ID_EVENTO":7459,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:32:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"dcruz@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:32:33.042Z","ID_EVENTO":7460,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:32:33"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:41:39.168Z","ID_EVENTO":7461,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:41:39"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:41:40.203Z","ID_EVENTO":7462,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:41:40"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:41:42.220Z","ID_EVENTO":7463,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:41:42"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mlopezp@quiniela.com","DESC_ERROR":"No fue posible extraer informacion 1","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-13T23:41:46.243Z","ID_EVENTO":7464,"ID_PROCESO":6,"MSG_ERROR":"Error de tipo string en Ejecucion de Procedimiento: 'No fue posible extraer informacion 1'.","level":"error","message":"Error ","timestamp":"2025-09-13 17:41:46"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"fgalan@quiniela.com","DESC_ERROR":"Registro ya existe Q_SURVIVOR","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-09-14T13:28:37.516Z","ID_EVENTO":7472,"ID_PROCESO":2,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Create: 'Registro ya existe Q_SURVIVOR'.","level":"error","message":"Error ","timestamp":"2025-09-14 07:28:37"}
